language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-27
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository

before_install:
  - cd 04_Implement/02_Source/
  - chmod +x gradlew

script:
  - ./gradlew connectedTest